### ISSUE TITLE
Checklist for icons

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mint-y-icons#114]
Inheriting from Adwaita instead of Mint-X, caused some gaps, which need to be filled.
Plus suggestions for better/new symbolics/icons.

- [x] camera-photo-symbolic ([Faba icon](https://github.com/snwh/faba-icon-theme/blob/master/Faba/symbolic/devices/camera-photo-symbolic.svg))
- [x] avatar-default-symbolic ([Faba icon](https://github.com/snwh/faba-icon-theme/blob/master/Faba/symbolic/status/avatar-default-symbolic.svg))
- [x] contact-new-symbolic (Faba)
- [x] extract-archive (missing in nemo-fileroller) ([Faba icon](https://github.com/snwh/faba-icon-theme/blob/master/Faba/16x16/actions/extract-archive.svg))
- [x] add-files-to-archive (missing in nemo-fileroller) ([Faba icon](https://github.com/snwh/faba-icon-theme/blob/master/Faba/16x16/actions/archive-insert.svg))
- [ ] `.iso` files (missing icon `application-x-cd-image`?) (`media-optical` from Adwaita)

**Comment by JosephMcc** [comment]
I removed view-fullscreen and view restore. I really didn't like those and the current ones fit better with the arrow style of some of the other symbolics.
